/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Backlog
         * @description バックログを ``rank, id`` 順で 1 往復返す。各 PBI に ``_etag`` と配下タスクを含む。
         */
        get: operations["read_backlog_api_products__product_id__backlog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/pbis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create
         * @description PBI を1件作成する。状態は必ず ``new`` から始まる（提案書 図6）。
         */
        post: operations["create_api_products__product_id__pbis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/pbis/{pbi_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get One
         * @description PBI を1件取得する。存在しない／論理削除済みは 404（存在を漏らさない）。
         */
        get: operations["get_one_api_products__product_id__pbis__pbi_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete
         * @description PBI を論理削除する（物理削除しない。D-07）。以後 GET は 404。
         */
        delete: operations["delete_api_products__product_id__pbis__pbi_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update
         * @description PBI を部分更新する。``status`` を動かすときだけ状態遷移の正当性を確かめる。
         */
        patch: operations["update_api_products__product_id__pbis__pbi_id__patch"];
        trace?: never;
    };
    "/api/products/{product_id}/pbis/{pbi_id}/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reorder
         * @description PBI を前後の要素の**間**へ並び替える。更新は移動した1件だけ（提案書 06章）。
         *
         *     移動先の直前・直後の PBI id（:class:`RankMove`）から、両者の ``rank`` の間に入る
         *     新しいランクをサーバーで生成し、移動した PBI の ``rank`` だけを書き換える。整数 order の
         *     ように後続を巻き込まない（更新は常に1ドキュメント）。``If-Match`` は移動対象の
         *     ``_etag``（欠落 428・不一致 412）。
         */
        post: operations["reorder_api_products__product_id__pbis__pbi_id__rank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/pbis/{pbi_id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Split
         * @description 分割元 ``pbi_id`` を親に持つ子 PBI を作成する（B-19）。
         *
         *     大きな PBI を割って別の PBI を切り出す。生成物は通常の PBI（状態は ``new`` から）で、
         *     ``parentPbiId`` に分割元の id を刻む——一覧から分割元を辿るための唯一の参照
         *     （提案書 04章）。分割元は**変更しない**ため、これは新規作成であり ``If-Match`` を要さない
         *     （更新経路 ``PATCH`` とは非対称。汎用 PATCH は ``parentPbiId`` を触らない — D-20）。
         *     分割元が無ければ **404**（存在しないものからは分割できない）。入力（子のフィールド）は
         *     :class:`PbiCreate` と同形——分割は「親を指す作成」であり、新しい入力語彙を増やさない。
         */
        post: operations["split_api_products__product_id__pbis__pbi_id__split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/sprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All
         * @description スプリントを**番号順**で一覧する。各要素が ``_etag`` を本文に持つ（D-20）。
         */
        get: operations["list_all_api_products__product_id__sprints_get"];
        put?: never;
        /**
         * Create
         * @description スプリントを1件作成する。状態は必ず ``planned`` から始まる。
         */
        post: operations["create_api_products__product_id__sprints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/sprints/{sprint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get One
         * @description スプリントを1件取得する。存在しない／論理削除済みは 404（存在を漏らさない）。
         */
        get: operations["get_one_api_products__product_id__sprints__sprint_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete
         * @description スプリントを論理削除する（物理削除しない。D-07）。以後 GET は 404。
         */
        delete: operations["delete_api_products__product_id__sprints__sprint_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update
         * @description スプリントを部分更新する。``status`` の遷移と期間の破れを更新前に確かめる。
         */
        patch: operations["update_api_products__product_id__sprints__sprint_id__patch"];
        trace?: never;
    };
    "/api/products/{product_id}/sprints/{sprint_id}/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Board
         * @description ボードを 1 往復返す。スプリント情報＋そのスプリントのタスク（各要素に ``_etag``）＋進捗。
         *
         *     スプリントが存在しない／論理削除済みなら 404（存在を漏らさない）。タスクは ``sprintId``
         *     が一致するもの（pbi・team を問わない）を ``rank, id`` 順で返す。進捗（2本バー＋営業日
         *     マーカー）は同じ ``tasks`` から数え、追加クエリを撃たない（B-24）。
         */
        get: operations["read_board_api_products__product_id__sprints__sprint_id__board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/sprints/{sprint_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close
         * @description スプリントを締める。未完了タスクを ``nextSprintId`` へ移し、状態を ``closed`` にする。
         */
        post: operations["close_api_products__product_id__sprints__sprint_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/sprints/{sprint_id}/close/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview
         * @description 締めたときに持ち越される一覧（未完了タスク）を返す。読み取りのみ（P-1）。
         */
        get: operations["preview_api_products__product_id__sprints__sprint_id__close_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/sprints/{sprint_id}/pbis/{pbi_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Include
         * @description PBI をスプリントに取り込む。配下の未完了タスクに ``sprintId`` を付ける（0件なら生成）。
         */
        post: operations["include_api_products__product_id__sprints__sprint_id__pbis__pbi_id__post"];
        /**
         * Exclude
         * @description PBI をスプリントから外す。未完了タスクのみ ``sprintId`` を戻す（完了は動かさない — I-5）。
         */
        delete: operations["exclude_api_products__product_id__sprints__sprint_id__pbis__pbi_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create
         * @description タスクを1件作成する。状態は必ず ``todo`` から始まる（提案書 図5）。
         *
         *     ``taskType`` の整合（I-3・I-4）を作成前に検証し、``pbi`` タスクは親 PBI の実在も確かめる。
         *     ``team`` タスク（親 PBI なし）も作成できる（B-20 の完了条件）。
         */
        post: operations["create_api_products__product_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get One
         * @description タスクを1件取得する。存在しない／論理削除済みは 404（存在を漏らさない）。
         */
        get: operations["get_one_api_products__product_id__tasks__task_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete
         * @description タスクを論理削除する（物理削除しない。D-07）。以後 GET は 404。
         */
        delete: operations["delete_api_products__product_id__tasks__task_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update
         * @description タスクを部分更新する。``status`` を動かすと ``completedAt`` を自動で刻む／消す。
         */
        patch: operations["update_api_products__product_id__tasks__task_id__patch"];
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Spa */
        get: operations["serve_spa__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptanceCriterion
         * @description 完了条件チェックリストの1項目（提案書 04章）。編集は B-18。
         */
        AcceptanceCriterion: {
            /**
             * Checked
             * @default false
             */
            checked: boolean;
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /**
         * BacklogPbi
         * @description バックログ 1 行分の PBI。単一 GET の :class:`~app.api.pbis.Pbi` に ``_etag`` と
         *     **配下タスク**を足す。
         *
         *     集約 GET では版（``_etag``）を**本文のフィールド**として返す（D-20）。フロントはこの値を
         *     そのまま並び替え・ステータス変更の ``If-Match`` に使う。``_etag`` は先頭が下線のため
         *     Pydantic では別名を張る（フィールド名は ``etag``・入出力の別名は ``_etag``）。``tasks`` は
         *     この PBI を親に持つ pbi タスクを ``rank, id`` 順で並べたもの（無ければ空配列）。
         */
        BacklogPbi: {
            /** Etag */
            _etag: string;
            /** Acceptancecriteria */
            acceptanceCriteria: components["schemas"]["AcceptanceCriterion"][];
            /** Completedat */
            completedAt: string | null;
            /** Completedsprintid */
            completedSprintId: string | null;
            /** Createdat */
            createdAt: string;
            /** Createdby */
            createdBy: string;
            /** Description */
            description: string;
            /** Estimate */
            estimate: number | null;
            /** Id */
            id: string;
            /** Isdeleted */
            isDeleted: boolean;
            /** Parentpbiid */
            parentPbiId: string | null;
            /** Productid */
            productId: string;
            /** Rank */
            rank: string | null;
            status: components["schemas"]["PbiStatus"];
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["BacklogTask"][];
            /** Title */
            title: string;
            /** Type */
            type: string;
            /** Updatedat */
            updatedAt: string;
            /** Updatedby */
            updatedBy: string;
        };
        /**
         * BacklogResponse
         * @description プロダクトバックログ画面の集約応答（B-17・D-20）。
         *
         *     PBI 一覧（各 PBI は配下タスクを ``tasks`` に持つ。B-20）。未割当チームタスクは B-29 で
         *     ``unassignedTeamTasks`` として足すため、**オブジェクトで包む**（フィールド追加で拡張でき、
         *     素の配列のように破壊的にならない）。
         */
        BacklogResponse: {
            /** Pbis */
            pbis: components["schemas"]["BacklogPbi"][];
        };
        /**
         * BacklogTask
         * @description バックログの PBI 配下に並ぶタスク。単一 GET の :class:`~app.api.tasks.Task` に
         *     ``_etag`` を足す（集約の各要素が版を本文で持つのは BacklogPbi と同じ理由 — D-20）。
         */
        BacklogTask: {
            /** Etag */
            _etag: string;
            /** Assigneeid */
            assigneeId: string | null;
            /** Blockedreason */
            blockedReason: string;
            /** Completedat */
            completedAt: string | null;
            /** Createdat */
            createdAt: string;
            /** Createdby */
            createdBy: string;
            /** Id */
            id: string;
            /** Isblocked */
            isBlocked: boolean;
            /** Isdeleted */
            isDeleted: boolean;
            /** Memo */
            memo: string;
            /** Pbiid */
            pbiId: string | null;
            /** Productid */
            productId: string;
            /** Rank */
            rank: string | null;
            /** Sprintid */
            sprintId: string | null;
            status: components["schemas"]["TaskStatus"];
            taskType: components["schemas"]["TaskType"];
            /** Title */
            title: string;
            /** Todo */
            todo: string;
            /** Type */
            type: string;
            /** Updatedat */
            updatedAt: string;
            /** Updatedby */
            updatedBy: string;
        };
        /**
         * BoardResponse
         * @description スプリント画面の集約応答（B-23・B-24・D-20）。
         *
         *     ``sprint`` はボード見出しの表示に使う（この画面ではスプリント自身は更新しないため
         *     ``_etag`` は持たせない。編集導線が要るのは終了処理 B-25）。``tasks`` はこのスプリントに
         *     属するタスクを ``rank, id`` 順で並べたもの（各要素が ``_etag`` を持つ）。``progress`` は
         *     2本バーの分子分母＋営業日マーカー（B-24）。件数は ``tasks`` から数えるだけで追加クエリを
         *     撃たない。
         */
        BoardResponse: {
            progress: components["schemas"]["Progress"];
            sprint: components["schemas"]["Sprint"];
            /** Tasks */
            tasks: components["schemas"]["BoardTask"][];
        };
        /**
         * BoardTask
         * @description ボードに並ぶタスク。単一 GET の :class:`~app.api.tasks.Task` に ``_etag`` を足す
         *     （集約の各要素が版を本文で持つのは BacklogTask と同じ理由 — D-20）。
         */
        BoardTask: {
            /** Etag */
            _etag: string;
            /** Assigneeid */
            assigneeId: string | null;
            /** Blockedreason */
            blockedReason: string;
            /** Completedat */
            completedAt: string | null;
            /** Createdat */
            createdAt: string;
            /** Createdby */
            createdBy: string;
            /** Id */
            id: string;
            /** Isblocked */
            isBlocked: boolean;
            /** Isdeleted */
            isDeleted: boolean;
            /** Memo */
            memo: string;
            /** Pbiid */
            pbiId: string | null;
            /** Productid */
            productId: string;
            /** Rank */
            rank: string | null;
            /** Sprintid */
            sprintId: string | null;
            status: components["schemas"]["TaskStatus"];
            taskType: components["schemas"]["TaskType"];
            /** Title */
            title: string;
            /** Todo */
            todo: string;
            /** Type */
            type: string;
            /** Updatedat */
            updatedAt: string;
            /** Updatedby */
            updatedBy: string;
        };
        /**
         * CarryOverTask
         * @description 持ち越しプレビューの1行。人が「何が次へ移るか」を読める最小限に絞る。
         *
         *     プレビューは事実を見せるだけ（P-1）なので版（``_etag``）は載せない——確定
         *     （``POST .../close``）は ``If-Match`` を取らないサーバー所有の操作で、クライアントが
         *     個々のタスクの版を運ぶ必要がないため（ボードの :class:`BoardTask` とは非対称）。
         */
        CarryOverTask: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            taskType: components["schemas"]["TaskType"];
            /** Title */
            title: string;
        };
        /**
         * ClosePreview
         * @description 締めたときに持ち越される一覧（このスプリントの未完了タスク）。完了タスクは含めない（I-5）。
         */
        ClosePreview: {
            /** Tasks */
            tasks: components["schemas"]["CarryOverTask"][];
        };
        /**
         * CloseRequest
         * @description スプリント終了の確定入力。未完了タスクの**移動先スプリント**を指定する。
         *
         *     ``nextSprintId`` は既存の別スプリント（``planned`` or ``active``）を指す。フロントは
         *     「次スプリント」を先に作ってからその id を渡す（提案書 07章 ``sprintId = <nextSprintId>``）。
         */
        CloseRequest: {
            /** Nextsprintid */
            nextSprintId: string;
        };
        /**
         * CloseResult
         * @description スプリント終了の結果。締めたスプリントと**持ち越した件数**を返す（事実の提示 — P-1）。
         */
        CloseResult: {
            /** Carriedover */
            carriedOver: number;
            sprint: components["schemas"]["Sprint"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MeResponse
         * @description 認証済みユーザーと所属プロダクト一覧（B-10・D-21）。
         *
         *     ``products`` が空＝どのプロダクトにも属していない（未招待ユーザーに見せる画面の
         *     判定に使える）。``isGuest`` はゲストと実ユーザーで同じ形を保つための旗。
         */
        MeResponse: {
            /** Displayname */
            displayName?: string | null;
            /**
             * Isguest
             * @default false
             */
            isGuest: boolean;
            /** Oid */
            oid: string;
            /**
             * Products
             * @default []
             */
            products: components["schemas"]["ProductSummary"][];
        };
        /**
         * Pbi
         * @description PBI の応答表現（提案書 04章のフィールド）。
         *
         *     保存ドキュメントから組み立てる。``_etag`` は本文に載せず ``ETag`` ヘッダで返すため
         *     ``extra='ignore'`` で捨てる（単一ドキュメント応答の版はヘッダが正 — D-20）。
         */
        Pbi: {
            /** Acceptancecriteria */
            acceptanceCriteria: components["schemas"]["AcceptanceCriterion"][];
            /** Completedat */
            completedAt: string | null;
            /** Completedsprintid */
            completedSprintId: string | null;
            /** Createdat */
            createdAt: string;
            /** Createdby */
            createdBy: string;
            /** Description */
            description: string;
            /** Estimate */
            estimate: number | null;
            /** Id */
            id: string;
            /** Isdeleted */
            isDeleted: boolean;
            /** Parentpbiid */
            parentPbiId: string | null;
            /** Productid */
            productId: string;
            /** Rank */
            rank: string | null;
            status: components["schemas"]["PbiStatus"];
            /** Title */
            title: string;
            /** Type */
            type: string;
            /** Updatedat */
            updatedAt: string;
            /** Updatedby */
            updatedBy: string;
        };
        /**
         * PbiCreate
         * @description PBI 作成の入力。``title`` 以外は任意（未設定は既定値）。
         */
        PbiCreate: {
            /**
             * Acceptancecriteria
             * @default []
             */
            acceptanceCriteria: components["schemas"]["AcceptanceCriterion"][];
            /**
             * Description
             * @default
             */
            description: string;
            /** Estimate */
            estimate?: number | null;
            /** Title */
            title: string;
        };
        /**
         * PbiStatus
         * @description PBI の状態（提案書 04章・図6）。
         *
         *     タスクの ``todo`` / ``doing`` / ``done`` とは別の語彙を持つ。前進のみで、``done`` は
         *     終端（タスクと違い完了取り消しの戻り遷移を持たない — 完了地は不変。提案書 図6）。
         * @enum {string}
         */
        PbiStatus: "new" | "ready" | "inProgress" | "done";
        /**
         * PbiUpdate
         * @description PBI 更新の入力（部分更新）。**送られたフィールドだけ**を反映する。
         *
         *     ``rank`` / ``parentPbiId`` / ``completedAt`` / ``completedSprintId`` は載せない。
         *     それぞれ並び替え（B-16）・分割（B-19）・スプリント終了（B-25）が所有し、汎用 PATCH
         *     では動かさない（クライアントに完了地やランクの規則を漏らさない）。
         */
        PbiUpdate: {
            /** Acceptancecriteria */
            acceptanceCriteria?: components["schemas"]["AcceptanceCriterion"][] | null;
            /** Description */
            description?: string | null;
            /** Estimate */
            estimate?: number | null;
            status?: components["schemas"]["PbiStatus"] | null;
            /** Title */
            title?: string | null;
        };
        /**
         * Problem
         * @description RFC 9457 の problem 本体。OpenAPI にも載せ、フロントの型生成が拾う（D-20）。
         */
        Problem: {
            /**
             * Detail
             * @default null
             */
            detail: string | null;
            /**
             * Instance
             * @default null
             */
            instance: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
            /**
             * Violations
             * @default null
             */
            violations: components["schemas"]["Violation"][] | null;
        };
        /**
         * ProductSummary
         * @description 所属一覧の1要素。フロントのプロダクトセレクタが並べる（D-21）。
         */
        ProductSummary: {
            /** Name */
            name: string;
            /** Productid */
            productId: string;
            /** Role */
            role: string;
        };
        /**
         * Progress
         * @description スプリントの進捗（2本バー＋営業日マーカー。B-24・提案書 05章）。
         *
         *     ``planned``（計画タスク＝ ``taskType='pbi'``）と ``team``（チームタスク＝
         *     ``taskType='team'``）の2本を返す。マーカー位置は ``elapsedBusinessDays /
         *     totalBusinessDays``（経過営業日 ÷ 総営業日）。期間（``startDate`` / ``endDate``）が
         *     未設定なら営業日は **``null``**——フロントはマーカーを描かない（P-1）。
         */
        Progress: {
            /** Elapsedbusinessdays */
            elapsedBusinessDays: number | null;
            planned: components["schemas"]["ProgressBar"];
            team: components["schemas"]["ProgressBar"];
            /** Totalbusinessdays */
            totalBusinessDays: number | null;
        };
        /**
         * ProgressBar
         * @description 2本バーの1本（完了 ``done`` / 総数 ``total``。提案書 05章）。
         */
        ProgressBar: {
            /** Done */
            done: number;
            /** Total */
            total: number;
        };
        /**
         * RankMove
         * @description 並び替えの移動先を**前後の要素 ID** で指定する（D-20）。
         *
         *     ランクそのものはクライアントに作らせない。移動先の直前・直後の要素 ID だけを受け取り、
         *     サーバーが両者の ``rank`` の**間**に入る新しいランクを生成する（アルゴリズムを1箇所に
         *     閉じ、フロントを差し替えても挙動が変わらない — 提案書 06章）。
         *
         *     * ``beforeId`` — 移動先の**直前**（1つ上・rank が小さい方）の PBI id。先頭へ動かす
         *       場合は ``null``。
         *     * ``afterId`` — 移動先の**直後**（1つ下・rank が大きい方）の PBI id。末尾へ動かす
         *       場合は ``null``。
         *
         *     両方 ``null`` は「並びに他の要素が無い（唯一の要素）」を表す。
         */
        RankMove: {
            /** Afterid */
            afterId?: string | null;
            /** Beforeid */
            beforeId?: string | null;
        };
        /**
         * Sprint
         * @description スプリントの応答表現（提案書 04章のフィールド）。
         *
         *     単一ドキュメント応答（作成・取得・更新）では ``_etag`` を本文に載せず ``ETag``
         *     ヘッダで返すため ``extra='ignore'`` で捨てる。一覧は :class:`SprintListItem` が
         *     ``_etag`` を本文に持たせる（集約 GET と同じ非対称 — D-20）。
         */
        Sprint: {
            /** Createdat */
            createdAt: string;
            /** Createdby */
            createdBy: string;
            /** Enddate */
            endDate: string | null;
            /** Goal */
            goal: string;
            /** Id */
            id: string;
            /** Isdeleted */
            isDeleted: boolean;
            /** Number */
            number: number;
            /** Productid */
            productId: string;
            /** Startdate */
            startDate: string | null;
            status: components["schemas"]["SprintStatus"];
            /** Type */
            type: string;
            /** Updatedat */
            updatedAt: string;
            /** Updatedby */
            updatedBy: string;
        };
        /**
         * SprintCreate
         * @description スプリント作成の入力。期間・ゴールは任意（計画中は未定のことがある）。
         *
         *     ``number`` はサーバーが連番採番するため受け取らない（クライアントに採番させない）。
         *     ``status`` も受け取らない——作成時は必ず ``planned`` から始まる。
         */
        SprintCreate: {
            /** Enddate */
            endDate?: string | null;
            /**
             * Goal
             * @default
             */
            goal: string;
            /** Startdate */
            startDate?: string | null;
        };
        /**
         * SprintListItem
         * @description 一覧の1要素。集約 GET と同じく各要素が版（``_etag``）を本文で運ぶ（D-20）。
         *
         *     一覧応答全体では単一の ``ETag`` を返せないため、フロントは各要素の ``_etag`` を
         *     そのスプリントへの ``PATCH`` / ``DELETE`` の ``If-Match`` にそのまま載せる。
         */
        SprintListItem: {
            /** Etag */
            _etag: string;
            /** Createdat */
            createdAt: string;
            /** Createdby */
            createdBy: string;
            /** Enddate */
            endDate: string | null;
            /** Goal */
            goal: string;
            /** Id */
            id: string;
            /** Isdeleted */
            isDeleted: boolean;
            /** Number */
            number: number;
            /** Productid */
            productId: string;
            /** Startdate */
            startDate: string | null;
            status: components["schemas"]["SprintStatus"];
            /** Type */
            type: string;
            /** Updatedat */
            updatedAt: string;
            /** Updatedby */
            updatedBy: string;
        };
        /**
         * SprintStatus
         * @description スプリントの状態（提案書 04章 ``status:"planned | active | closed"``）。
         *
         *     PBI の ``new`` / ``ready`` / … やタスクの ``todo`` / ``doing`` / ``done`` とは別の
         *     語彙。前進のみで、``closed`` は終端（終了処理 B-25 を経た後は戻さない）。
         * @enum {string}
         */
        SprintStatus: "planned" | "active" | "closed";
        /**
         * SprintUpdate
         * @description スプリント更新の入力（部分更新）。**送られたフィールドだけ**を反映する。
         *
         *     ``number`` は載せない（採番はサーバーが所有し、後から振り直さない）。``status`` は
         *     状態機械（planned → active → closed）を通してのみ動かす。
         */
        SprintUpdate: {
            /** Enddate */
            endDate?: string | null;
            /** Goal */
            goal?: string | null;
            /** Startdate */
            startDate?: string | null;
            status?: components["schemas"]["SprintStatus"] | null;
        };
        /**
         * Task
         * @description タスクの応答表現（提案書 04章のフィールド）。
         *
         *     ``_etag`` は本文に載せず ``ETag`` ヘッダで返すため ``extra='ignore'`` で捨てる
         *     （単一ドキュメント応答の版はヘッダが正 — D-20）。
         */
        Task: {
            /** Assigneeid */
            assigneeId: string | null;
            /** Blockedreason */
            blockedReason: string;
            /** Completedat */
            completedAt: string | null;
            /** Createdat */
            createdAt: string;
            /** Createdby */
            createdBy: string;
            /** Id */
            id: string;
            /** Isblocked */
            isBlocked: boolean;
            /** Isdeleted */
            isDeleted: boolean;
            /** Memo */
            memo: string;
            /** Pbiid */
            pbiId: string | null;
            /** Productid */
            productId: string;
            /** Rank */
            rank: string | null;
            /** Sprintid */
            sprintId: string | null;
            status: components["schemas"]["TaskStatus"];
            taskType: components["schemas"]["TaskType"];
            /** Title */
            title: string;
            /** Todo */
            todo: string;
            /** Type */
            type: string;
            /** Updatedat */
            updatedAt: string;
            /** Updatedby */
            updatedBy: string;
        };
        /**
         * TaskCreate
         * @description タスク作成の入力。``taskType`` が判別子で必ず持つ（I-4）。
         *
         *     ``taskType='pbi'`` なら ``pbiId`` が必須（I-3）、``taskType='team'`` なら ``pbiId`` は
         *     ``null``（I-4）。整合はサーバーが :func:`~app.data.tasks.check_invariants` で確かめる。
         *     作成はタイトルだけの**クイック追加**に絞る（``todo`` / ``memo`` / ``assigneeId`` の編集は
         *     後から ``PATCH`` で足す — タスク詳細の作り込みは本 PBI の範囲外）。``sprintId`` / ``rank`` /
         *     ``status`` も入力に取らない（プランニング B-22・ボード B-23 が所有し、作成時は必ず
         *     ``todo`` 状態 / ``sprintId=null``）。
         */
        TaskCreate: {
            /** Pbiid */
            pbiId?: string | null;
            taskType: components["schemas"]["TaskType"];
            /** Title */
            title: string;
        };
        /**
         * TaskStatus
         * @description タスクの状態（提案書 図5）。
         *
         *     PBI の状態（``new`` … ``done``）とは別の語彙。ボード上を ``todo`` / ``doing`` /
         *     ``done`` の間で自由に行き来する（PBI と違い一方向ではない — 完了取り消しがある。
         *     その戻し遷移で ``completedAt`` を ``null`` へ戻すのが I-1・I-2）。
         * @enum {string}
         */
        TaskStatus: "todo" | "doing" | "done";
        /**
         * TaskType
         * @description タスクの種別（提案書 04章・図5）。**判別子であり、必ず持つ**。
         * @enum {string}
         */
        TaskType: "pbi" | "team";
        /**
         * TaskUpdate
         * @description タスク更新の入力（部分更新）。**送られたフィールドだけ**を反映する。
         *
         *     ``taskType`` / ``pbiId`` は載せない（作成時に確定する判別子。後から種別を変えると
         *     バックログの束ね方 I-3・I-4 が崩れる）。``completedAt`` も載せない — ``status`` を
         *     ``done`` に動かすとサーバーが自動で刻む（:func:`~app.data.tasks.completion_changes`）。
         *     ``sprintId`` はプランニング（B-22）、``rank`` はボード（B-23）が専用経路で動かす。
         */
        TaskUpdate: {
            /** Assigneeid */
            assigneeId?: string | null;
            /** Blockedreason */
            blockedReason?: string | null;
            /** Isblocked */
            isBlocked?: boolean | null;
            /** Memo */
            memo?: string | null;
            status?: components["schemas"]["TaskStatus"] | null;
            /** Title */
            title?: string | null;
            /** Todo */
            todo?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Violation
         * @description ``violations`` の 1 要素。**どの規則で弾いたか**を機械可読にする（D-20）。
         *
         *     ``rule`` は不変条件 ID（``I-4`` など）。リクエストバリデーション由来のときは
         *     pydantic のエラー種別（``missing`` など）を入れる。``field`` は対象フィールド
         *     （不明・複数なら ``None``）。
         */
        Violation: {
            /**
             * Field
             * @default null
             */
            field: string | null;
            /** Message */
            message: string;
            /** Rule */
            rule: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    read_backlog_api_products__product_id__backlog_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacklogResponse"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_api_products__product_id__pbis_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PbiCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pbi"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_one_api_products__product_id__pbis__pbi_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pbi_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pbi"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_api_products__product_id__pbis__pbi_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pbi_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_api_products__product_id__pbis__pbi_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pbi_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PbiUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pbi"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    reorder_api_products__product_id__pbis__pbi_id__rank_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pbi_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankMove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pbi"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    split_api_products__product_id__pbis__pbi_id__split_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pbi_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PbiCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pbi"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_all_api_products__product_id__sprints_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintListItem"][];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_api_products__product_id__sprints_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SprintCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sprint"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_one_api_products__product_id__sprints__sprint_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sprint"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_api_products__product_id__sprints__sprint_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_api_products__product_id__sprints__sprint_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SprintUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sprint"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    read_board_api_products__product_id__sprints__sprint_id__board_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    close_api_products__product_id__sprints__sprint_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloseResult"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    preview_api_products__product_id__sprints__sprint_id__close_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosePreview"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    include_api_products__product_id__sprints__sprint_id__pbis__pbi_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                pbi_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    exclude_api_products__product_id__sprints__sprint_id__pbis__pbi_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sprint_id: string;
                pbi_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_api_products__product_id__tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_one_api_products__product_id__tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_api_products__product_id__tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_api_products__product_id__tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    serve_spa__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
