/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Spa */
        get: operations["serve_spa__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MeResponse
         * @description 認証済みユーザーと所属プロダクト一覧（B-10・D-21）。
         *
         *     ``products`` が空＝どのプロダクトにも属していない（未招待ユーザーに見せる画面の
         *     判定に使える）。``isGuest`` はゲストと実ユーザーで同じ形を保つための旗。
         */
        MeResponse: {
            /** Displayname */
            displayName?: string | null;
            /**
             * Isguest
             * @default false
             */
            isGuest: boolean;
            /** Oid */
            oid: string;
            /**
             * Products
             * @default []
             */
            products: components["schemas"]["ProductSummary"][];
        };
        /**
         * Problem
         * @description RFC 9457 の problem 本体。OpenAPI にも載せ、フロントの型生成が拾う（D-20）。
         */
        Problem: {
            /**
             * Detail
             * @default null
             */
            detail: string | null;
            /**
             * Instance
             * @default null
             */
            instance: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
            /**
             * Violations
             * @default null
             */
            violations: components["schemas"]["Violation"][] | null;
        };
        /**
         * ProductSummary
         * @description 所属一覧の1要素。フロントのプロダクトセレクタが並べる（D-21）。
         */
        ProductSummary: {
            /** Name */
            name: string;
            /** Productid */
            productId: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Violation
         * @description ``violations`` の 1 要素。**どの規則で弾いたか**を機械可読にする（D-20）。
         *
         *     ``rule`` は不変条件 ID（``I-4`` など）。リクエストバリデーション由来のときは
         *     pydantic のエラー種別（``missing`` など）を入れる。``field`` は対象フィールド
         *     （不明・複数なら ``None``）。
         */
        Violation: {
            /**
             * Field
             * @default null
             */
            field: string | null;
            /** Message */
            message: string;
            /** Rule */
            rule: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    serve_spa__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
