/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/pbis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create
         * @description PBI を1件作成する。状態は必ず ``new`` から始まる（提案書 図6）。
         */
        post: operations["create_api_products__product_id__pbis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/pbis/{pbi_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get One
         * @description PBI を1件取得する。存在しない／論理削除済みは 404（存在を漏らさない）。
         */
        get: operations["get_one_api_products__product_id__pbis__pbi_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete
         * @description PBI を論理削除する（物理削除しない。D-07）。以後 GET は 404。
         */
        delete: operations["delete_api_products__product_id__pbis__pbi_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update
         * @description PBI を部分更新する。``status`` を動かすときだけ状態遷移の正当性を確かめる。
         */
        patch: operations["update_api_products__product_id__pbis__pbi_id__patch"];
        trace?: never;
    };
    "/api/products/{product_id}/pbis/{pbi_id}/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reorder
         * @description PBI を前後の要素の**間**へ並び替える。更新は移動した1件だけ（提案書 06章）。
         *
         *     移動先の直前・直後の PBI id（:class:`RankMove`）から、両者の ``rank`` の間に入る
         *     新しいランクをサーバーで生成し、移動した PBI の ``rank`` だけを書き換える。整数 order の
         *     ように後続を巻き込まない（更新は常に1ドキュメント）。``If-Match`` は移動対象の
         *     ``_etag``（欠落 428・不一致 412）。
         */
        post: operations["reorder_api_products__product_id__pbis__pbi_id__rank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Spa */
        get: operations["serve_spa__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptanceCriterion
         * @description 完了条件チェックリストの1項目（提案書 04章）。編集は B-18。
         */
        AcceptanceCriterion: {
            /**
             * Checked
             * @default false
             */
            checked: boolean;
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MeResponse
         * @description 認証済みユーザーと所属プロダクト一覧（B-10・D-21）。
         *
         *     ``products`` が空＝どのプロダクトにも属していない（未招待ユーザーに見せる画面の
         *     判定に使える）。``isGuest`` はゲストと実ユーザーで同じ形を保つための旗。
         */
        MeResponse: {
            /** Displayname */
            displayName?: string | null;
            /**
             * Isguest
             * @default false
             */
            isGuest: boolean;
            /** Oid */
            oid: string;
            /**
             * Products
             * @default []
             */
            products: components["schemas"]["ProductSummary"][];
        };
        /**
         * Pbi
         * @description PBI の応答表現（提案書 04章のフィールド）。
         *
         *     保存ドキュメントから組み立てる。``_etag`` は本文に載せず ``ETag`` ヘッダで返すため
         *     ``extra='ignore'`` で捨てる（単一ドキュメント応答の版はヘッダが正 — D-20）。
         */
        Pbi: {
            /** Acceptancecriteria */
            acceptanceCriteria: components["schemas"]["AcceptanceCriterion"][];
            /** Completedat */
            completedAt: string | null;
            /** Completedsprintid */
            completedSprintId: string | null;
            /** Createdat */
            createdAt: string;
            /** Createdby */
            createdBy: string;
            /** Description */
            description: string;
            /** Estimate */
            estimate: number | null;
            /** Id */
            id: string;
            /** Isdeleted */
            isDeleted: boolean;
            /** Parentpbiid */
            parentPbiId: string | null;
            /** Productid */
            productId: string;
            /** Rank */
            rank: string | null;
            status: components["schemas"]["PbiStatus"];
            /** Title */
            title: string;
            /** Type */
            type: string;
            /** Updatedat */
            updatedAt: string;
            /** Updatedby */
            updatedBy: string;
        };
        /**
         * PbiCreate
         * @description PBI 作成の入力。``title`` 以外は任意（未設定は既定値）。
         */
        PbiCreate: {
            /**
             * Acceptancecriteria
             * @default []
             */
            acceptanceCriteria: components["schemas"]["AcceptanceCriterion"][];
            /**
             * Description
             * @default
             */
            description: string;
            /** Estimate */
            estimate?: number | null;
            /** Title */
            title: string;
        };
        /**
         * PbiStatus
         * @description PBI の状態（提案書 04章・図6）。
         *
         *     タスクの ``todo`` / ``doing`` / ``done`` とは別の語彙を持つ。前進のみで、``done`` は
         *     終端（タスクと違い完了取り消しの戻り遷移を持たない — 完了地は不変。提案書 図6）。
         * @enum {string}
         */
        PbiStatus: "new" | "ready" | "inProgress" | "done";
        /**
         * PbiUpdate
         * @description PBI 更新の入力（部分更新）。**送られたフィールドだけ**を反映する。
         *
         *     ``rank`` / ``parentPbiId`` / ``completedAt`` / ``completedSprintId`` は載せない。
         *     それぞれ並び替え（B-16）・分割（B-19）・スプリント終了（B-25）が所有し、汎用 PATCH
         *     では動かさない（クライアントに完了地やランクの規則を漏らさない）。
         */
        PbiUpdate: {
            /** Acceptancecriteria */
            acceptanceCriteria?: components["schemas"]["AcceptanceCriterion"][] | null;
            /** Description */
            description?: string | null;
            /** Estimate */
            estimate?: number | null;
            status?: components["schemas"]["PbiStatus"] | null;
            /** Title */
            title?: string | null;
        };
        /**
         * Problem
         * @description RFC 9457 の problem 本体。OpenAPI にも載せ、フロントの型生成が拾う（D-20）。
         */
        Problem: {
            /**
             * Detail
             * @default null
             */
            detail: string | null;
            /**
             * Instance
             * @default null
             */
            instance: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
            /**
             * Violations
             * @default null
             */
            violations: components["schemas"]["Violation"][] | null;
        };
        /**
         * ProductSummary
         * @description 所属一覧の1要素。フロントのプロダクトセレクタが並べる（D-21）。
         */
        ProductSummary: {
            /** Name */
            name: string;
            /** Productid */
            productId: string;
            /** Role */
            role: string;
        };
        /**
         * RankMove
         * @description 並び替えの移動先を**前後の要素 ID** で指定する（D-20）。
         *
         *     ランクそのものはクライアントに作らせない。移動先の直前・直後の要素 ID だけを受け取り、
         *     サーバーが両者の ``rank`` の**間**に入る新しいランクを生成する（アルゴリズムを1箇所に
         *     閉じ、フロントを差し替えても挙動が変わらない — 提案書 06章）。
         *
         *     * ``beforeId`` — 移動先の**直前**（1つ上・rank が小さい方）の PBI id。先頭へ動かす
         *       場合は ``null``。
         *     * ``afterId`` — 移動先の**直後**（1つ下・rank が大きい方）の PBI id。末尾へ動かす
         *       場合は ``null``。
         *
         *     両方 ``null`` は「並びに他の要素が無い（唯一の要素）」を表す。
         */
        RankMove: {
            /** Afterid */
            afterId?: string | null;
            /** Beforeid */
            beforeId?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Violation
         * @description ``violations`` の 1 要素。**どの規則で弾いたか**を機械可読にする（D-20）。
         *
         *     ``rule`` は不変条件 ID（``I-4`` など）。リクエストバリデーション由来のときは
         *     pydantic のエラー種別（``missing`` など）を入れる。``field`` は対象フィールド
         *     （不明・複数なら ``None``）。
         */
        Violation: {
            /**
             * Field
             * @default null
             */
            field: string | null;
            /** Message */
            message: string;
            /** Rule */
            rule: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    create_api_products__product_id__pbis_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PbiCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pbi"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_one_api_products__product_id__pbis__pbi_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pbi_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pbi"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_api_products__product_id__pbis__pbi_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pbi_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Problem */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_api_products__product_id__pbis__pbi_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pbi_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PbiUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pbi"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    reorder_api_products__product_id__pbis__pbi_id__rank_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pbi_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankMove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pbi"];
                };
            };
            /** @description Problem */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    serve_spa__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
